# REST API

### Root Test
GET http://localhost:3000/

### About
GET http://localhost:3000/about

### Get All Profile
GET http://localhost:3000/profile
### curl -X POST  http://localhost:3000/profile
POST http://localhost:3000/profile
Content-Type: application/json

{
  "username": "thanusphol",
  "password": "Bhun0988014838zazazazaza!",
  "mobile": "0988014838",
  "cardId": "1234764777777"
}